### ISSUE TITLE
A few missing files from 2022

### ISSUE THREAD

**Issue by prabowo02** [Arkavidia-CP/arkavidia-cp-problemset#2]
There are a few missing files and I am unable to generate the test files for the corresponding problems:

- `solution.cpp` for `arkavidia-2022-final-arka-sang-pencuri`
- `spec.cpp` for `arkavidia-2022-final-hexagame`

Could you kindly help adding those missing files?

**Comment by airathalca** [comment]
I've already uploaded a zip file containing test cases for some questions. For questions without zip files for test cases, they can be generated manually. Apologize for forgetting to push the solution for the final A question.

**Comment by prabowo02** [comment]
Thanks, but what I meant was there is no `spec.cpp` for Final H, so I can't generate the test files only for Final H.

I think you can remove all the zip files to keep the repo small.

**Comment by airathalca** [comment]
Still trying to find the 'spec.cpp' file for the final problem H, therefore I provide the zip file for problem H first. Im removing all zip files except for problem H

**Comment by prabowo02** [comment]
Thanks again!

We have uploaded the problems to TLX:

https://tlx.toki.id/problems/arkavidia-8-pc-penyisihan
https://tlx.toki.id/problems/arkavidia-8-pc-final

We appreciate your help in providing these contest materials
